### ISSUE TITLE
.flashTech() method not available

### ISSUE THREAD

**Issue by johndanek** [videojs/videojs-flash#11]
https://github.com/videojs/videojs-flash#script-tag

According to this example, the player should have a `.flashTech()` method attached after including the videojs-flash script. My script has been correctly loaded, but not flashTech method is available to my player object.

**Comment by BrandonOCasey** [comment]
This is actually some carryover boilderplate from [generator-videojs-plugin](). You shouldn't actually have to call `player.flashTech()`, as long as you include the `videojs-flash` script in your page, or include it with a bundler the Flash tech should be registered for you. From there you will have to do: `videojs('some-player-id', {techOrder: ['flash', 'html5']};` to force flash as a priority over HTML5. We do need to update the README in this project though, sorry about that!

**Comment by BrandonOCasey** [comment]
I am going to close this as [I have a PR](https://github.com/videojs/videojs-flash/pull/12) out to update the documentation a bit. Feel free to leave feedback in there or re-open this issue if you need more help!
