### ISSUE TITLE
Does flash fallback work?

### ISSUE THREAD

**Issue by kinjal-codes** [videojs/videojs-flash#122]
## Description
Briefly describe the issue.
Flash fallback for hls stream does not work at all. 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.
Open this url. https://codepen.io/anon/pen/NJjGyd

### Expected
It should play hls stream ?

### Actual
It's does not load flash player.

#### videojs
what version of videojs does this occur with?
7

#### browsers
all

#### OSes
Windows 10 and Windows 7

### plugins
No just videojs-flash

**Comment by mister-ben** [comment]
You also need the Flash HLS source handler:

https://github.com/brightcove/videojs-flashls-source-handler

**Comment by gkatsev** [comment]
Yeah, you'll want to grab the flashls source handler if you want HLS played back in Flash.
Also, be aware that a lot of browsers disable flash by default and there isn't much we can do as it's up to the user to allow flash on the site.

**Comment by joelBrun** [comment]
Hello @kinjal-codes, 
Where you able to test the flash hls fallback? does it work ?

**Comment by gkatsev** [comment]
Just be aware that Flash is being end-of-lifed at the end of the year and modern browsers have it disabled by default and make it hard to use.
