### ISSUE TITLE
The object doesn't support the property or method "vjs_getProperty"

### ISSUE THREAD

**Issue by flaviohenriquecbc** [videojs/videojs-flash#138]
## Description
I'm receiving on New Relic the following error: "The object doesn't support the property or method 'vjs_getProperty'"

## Steps to reproduce
I couldn't reproduce it on BrowserStack, but the errors are reported for the IE11 users.

### Error output

![Screenshot 2019-09-05 at 14 39 30](https://user-images.githubusercontent.com/1553609/64342853-ae4c2200-cfeb-11e9-817f-8134785bf0f5.png)

### config
I'm using the following config:

```
{
    html5: {
        hls: {
            overrideNative: true,
            enableLowInitialPlaylist: true
        }
    },
    flash: {
        swf: './dist/asset/video-js.swf'
    },
    controlBar: {
        children: []
    },
    fluid: true,
    controls: true,
    preload: 'auto',
    playsinline: true,
    nativeControlsForTouch: false,
    languages: {
        de,
        en
    }
}
```

#### videojs
video.js@7.6.0/dist/alt/video.core.js
videojs-flash@version 2.2.0
@videojs/http-streaming@1.10.5

#### browsers
IE 11

**Comment by ewojjowe** [comment]
same here
