### ISSUE TITLE
i have some urls cant play

### ISSUE THREAD

**Issue by yuu2lee4** [videojs/videojs-flash#141]
i have some urls,some can play,and some cant play with videojs,but all can play with vlc.
rtmp://10.33.71.10:1935/live/pag/10.33.71.10/7302/62f07924a1654da4a7f2ab0fbd58ed06/0/SUB/TCP
-- | --
rtmp://10.33.71.10:1935/live/pag/10.33.71.10/7302/3dc1c534e09940e09fc544cd887b7dab/0/SUB/TCP
rtmp://10.33.71.10:1935/live/pag/10.33.71.10/7302/cd00c2176a6d4b3bb7590dd8714a15b6/0/SUB/TCP
rtmp://10.33.71.10:1935/live/pag/10.33.71.10/7302/881b18264d2b4770a55ca3bb932cc8d6/0/SUB/TCP
rtmp://10.33.71.10:1935/live/pag/10.33.71.10/7302/35b1bbace45d44ccbbf10e103d841ec7/0/SUB/TCP rtmp://10.33.71.10:1935/live/pag/10.33.71.10/7302/04d0136cd7eb4f4e8f89210b30283ce0/0/SUB/TCP

**Comment by gkatsev** [comment]
You need to split the connection url and stream name with an &. See our FAQ for an example https://docs.videojs.com/tutorial-faq.html#q%3A-how-can-i-play-rtmp-video-in-video.js%3F
