### ISSUE TITLE
bower package not found

### ISSUE THREAD

**Issue by emilz0r** [videojs/videojs-flash#19]
## Description
Tried to install with bower, but it failes.

## Steps to reproduce

1. bower install --save videojs-flash

### Expected
Expected bower to download videojs-flash from bower registry

### Actual
Error message in terminal saying the package is not found

### Error output
ENOTFOUND Package videojs-flash not found

#### videojs
6.1.0
#### OSes
windows 10

### plugins
videojs-youtube (from bower.json: "videojs-youtube": "^2.4.0")

**Comment by misteroneill** [comment]
@emilz0r The 2.0.0 version of videojs-flash removed support for Bower - as did the 6.0.0 version of Video.js itself. Unfortunately, supporting Bower caused too many headaches for the Video.js maintainers and forced us to do ugly things like checking in our `dist/` directory.

I'd suggest either installing via npm if possible or using [unpkg](https://unpkg.com/).

**Comment by emilz0r** [comment]
@misteroneill Thank you for your reply. We have decided to go with webpack (which even the bower team has recommended at one point).
