### ISSUE TITLE
Request: Please include a 'dist' directory with the *compiled* videojs-flash.js

### ISSUE THREAD

**Issue by GwynethLlewelyn** [videojs/videojs-flash#25]
Hi there,

I do _not_ use either `npm` or `bower`, so assembling the many bits (and dependencies!) used by videojs-flash has been a painful experience. At the end of the day, I had no choice but to attempt to set up a `npm` environment on one of my servers, just to run the command to build videojs-flash.js, and getting a lot of cryptic warnings (are they really warnings?):

```
$ npm install --save videojs-flash
▄ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine videojs-flash@2.0.0: wanted: {"node":">=4.4.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
npm WARN saveError ENOENT: no such file or directory, open '/home/gwyneth/package.json'
/home/gwyneth
└─┬ videojs-flash@2.0.0 
  ├─┬ global@4.3.2 
  │ ├─┬ min-document@2.19.0 
  │ │ └── dom-walk@0.1.1 
  │ └── process@0.5.2 
  ├─┬ video.js@6.2.0 
  │ ├─┬ babel-runtime@6.23.0 
  │ │ ├── core-js@2.4.1 
  │ │ └── regenerator-runtime@0.10.5 
  │ ├─┬ safe-json-parse@4.0.0 
  │ │ └─┬ rust-result@1.0.0 
  │ │   └── individual@2.0.0 
  │ ├── tsml@1.0.1 
  │ ├── videojs-font@2.0.0 
  │ ├─┬ videojs-ie8@1.1.2 
  │ │ └── es5-shim@4.5.9 
  │ ├── videojs-vtt.js@0.12.4 
  │ └─┬ xhr@2.4.0 
  │   ├── is-function@1.0.1 
  │   ├─┬ parse-headers@2.0.1 
  │   │ ├── for-each@0.3.2 
  │   │ └── trim@0.0.1 
  │   └── xtend@4.0.1 
  └── videojs-swf@5.4.0 

npm WARN enoent ENOENT: no such file or directory, open '/home/gwyneth/package.json'
npm WARN gwyneth No description
npm WARN gwyneth No repository field.
npm WARN gwyneth No README data
npm WARN gwyneth No license field.
```

All this, of course, conveniently hidden in a .npm directory which I found by mere chance, full of lovely directories with gazillions of `package.tgz`all over the place. De-tar-ing them eventually produced some meaningful `.js` files, some of which with dependencies called with surreal paths... oh well, I admit it, I'm neither a Node.js developer, much less interested in becoming one on short notice, all I need is a _working_ videojs-flash.js and that's it.

Most packages I've been using on GitHub kindly provide a 'dist' directory where everything has been properly compiled in with all dependencies and is ready to be used. I've tried to request `videojs-flash.js` to be added to `cdnjs` but I have no idea when it will be available; in the mean time, us non-Node.js developers are a bit stuck at how to get this working.

So, _please_, give us the pre-compiled `.js`on a 'dist' directory! Also, because I'm fond of adding submodules on my own GitHub projects, so that they can be independently updated, this would make things even easier that way — just like I do for so many others (as a bonus, this also means that your credits/license will be much more visible that way).

(Note: I _did_ make a few attempts to get it to play nicely with `video.js`; so far, I have not been lucky to figure out how to do it; I'm adding a separae issue with some questions and insights on what's wrong so far with my own configuration...)

**Comment by misteroneill** [comment]
As an organization, Video.js has decided that checking in the `dist/` directory is a bad practice. While many front-end projects ignore the distinction between source and distribution, we think it's important for maintainable software. This is related to our decision to drop support for Bower from our projects.

As an easy alternative to npm, you might check out [unpkg](https://unpkg.com/), which is a CDN hosting npm packages. For getting Video.js with videojs-flash and videojs-swf all together, you could use the following:

```html
<script src="https://unpkg.com/video.js@6.2.1/dist/video.min.js"></script>
<script src="https://unpkg.com/videojs-flash@2.0.0/dist/videojs-flash.min.js"></script>
<script>
  videojs.options.flash.swf = 'https://unpkg.com/videojs-swf@5.4.0/dist/video-js.swf';
</script>
```

We could definitely do a better job of documenting how to use Video.js 6 with Flash!

The error you're seeing is due to trying to `--save` videojs-flash as a dependency. If the file `/home/gwyneth/package.json` does not exist (i.e. you're trying to install to a directory that's not a Node project), you can safely leave the `--save` flag off.

Also, the `~/.npm` directory is not meant for human consumption!

**Comment by GwynethLlewelyn** [comment]
First of all, thank you so much for the explanation of your organisation's policies. I did not realise that there existed such policies at all; it only shows how much a beginner and an amateur I am in these issues.

Secondly, when I saw how easily this would work by just including the correct CDN-hosted packages, I could have kicked myself for having wasted so many hours in attempting to get it to work. It was almost with a masochistic delight that I got precisely the same error as before, which I'm going to add to #26 (since it is not pertinent to the issue here).

I totally agree that better documentation for the clueless newbie like me would be mostly appreciated! :) It's funny, though... I've spent the last two decades trying to set up video streaming in a way or another, and there is always something that eludes me. It took me years after the Darwin
 Streaming Server was released as open source to get it up and running; and when finally I got around in setting that up, and had a working and stable configuration, and several ways to view it from web pages... the industry moved along to RTMP, during the 'Flash Über Alles' days, and those who still used RTP/RTSP were laughed at for 'clinging to the past' and to 'proprietary solutions from Apple'. Years later, after _finally_ managing to get a working and stable Red5 configuration on the server side... the industry, once again, makes a paradigm shift, starts hating Flash with extreme prejudice (well, I _always_ hated it, I just wonder why it took so long :) ) and... goes back to RTP/RTSP, leaving me stumped at how to get Red5 to stream once again to a Web page. LOL! It's so ironic! Maybe I should just forget all about everything, and go back to old-and-faithful DSS, which I understand has been 'dead' for some 18 months down without new releases... and simply use Video.js for displaying a RTSP stream, something I _know_ it can do out-of-the-box.

Anyway, I'm back to reading some `npm` tutorials, because your suggestion just outputs the following:

```
gwyneth@autonomy:~$ npm install videojs-flash
▐ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine videojs-flash@2.0.0: wanted: {"node":">=4.4.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
/home/gwyneth
└── videojs-flash@2.0.0 

npm WARN enoent ENOENT: no such file or directory, open '/home/gwyneth/package.json'
npm WARN gwyneth No description
npm WARN gwyneth No repository field.
npm WARN gwyneth No README data
npm WARN gwyneth No license field.
```
and I get basically nothing except inside the `~/.npm` directory (just as before), which, even though it might not meant to be for human consumption, it's the only thing that `npm` apparently likes to spew out... (and no, `/home/gwyneth/package.json`does not exist, since I'm not creating any Node projects — certainly not on that server for sure :) )

Anyway, thanks for your help, and my apologies for my ranting. I have this thing with video streaming, somehow video is incompatible with _me_ personally — probably someone cursed me when I was little, I don't know :)

**Comment by gkatsev** [comment]
You should make sure you're in a project directory when running `npm install`, preferably with its own `package.json`. `npm install` always installs things locally into a `node_modules` directory, so, try looking in `/home/gwyneth/node_modules/`.
Something like:
```sh
$ mkdir test-project
$ cd test-project
$ npm init -y # just initialize an empty npm package with default answers
$ npm install videojs-flash
$ ls node_modules/videojs-flash
```
