### ISSUE TITLE
The infamous 'No compatible source was found for this media.' error

### ISSUE THREAD

**Issue by GwynethLlewelyn** [videojs/videojs-flash#26]
## Description
Basically I'm trying to get a live stream to be reproduced inside Video.js. It is captured using [Open Broadcaster Software](https://obsproject.com/) and sent to a [Red5 Media Server](http://red5.org/) (free version, not Pro). Red5 then streams it on demand using `rtmp`. VLC has absolutely no problem in getting the stream; and OBS has been used also to upstream to YouTube live, so we can assume for now that the configuration for upstreaming and broadcasting are correct.

All attempts to get videojs-flash working will give the infamous 'No compatible source was found for this media.' error; the Chrome console shows `VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.` on line 449 of video.js. The same error is found on Firefox and Safari (I've got a Mac so I didn't try IE/Edge, nor bothered to install Opera :) ); Firefox adds some more errors of its own. All of these have Flash support active (but apparently the detection code for Flash does not work for Chrome).

## Steps to reproduce
I'm trying the following minimalistic approach on a local HTML file. `video.js` is being called from `cdnjs`, but `videojs-flash.js` is also local, as well as the dependency `swf/5.4.0/video-js.swf` which I found out that was also needed. I'm not aware of further dependencies (?) and I'm not familiar with `npm` or `bower` (or even Node.js...) so I have no clue if anything else is needed ot not. Those files (as well as minimised versions and so forth) were produced after a `npm install --save videojs-flash` placed a lot of `package.tgz` inside `.npm`, which I presume to be the correct output for `npm` (?) — I've extracted those two and placed them locally as appropriate, and made sure that they could be opened and read by Chrome.

```html
<!DOCTYPE HTML>
<html>
<head>
        <meta charset="UTF-8">
        <link href="http://vjs.zencdn.net/6.2.0/video-js.css" rel="stylesheet">
        <script src="http://vjs.zencdn.net/6.2.0/video.js"></script>        
        <!-- If you'd like to support IE8 -->
        <script src="http://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
        <script src="videojs-flash.js"></script>
</head>

<body>
        <video
                id="my-video"
                class="video-js vjs-default-skin vjs-big-play-centered"
                controls
                preload="none"
                width="640"
                height="480"
                poster="http://vjs.zencdn.net/v/oceans.png"
                data-setup='{"techOrder": ["flash", "html5"],
                        "nativeControlsForTouch": true,
                        "controlBar": { "muteToggle": false, "volumeControl": false,
                        "timeDivider": false,
                        "durationDisplay": false,
                        "progressControl": false } }'>
                <source src="rtmp://my.server.address/live/&mystreamname"
                        type="rtmp/mp4">

                <p class="vjs-no-js">
                            To view this video please enable JavaScript, and
                            consider upgrading to a web browser that
                        <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
                </p>
        </video>
</body>
</html>
```
Note that the browser will show the 'poster' image and starts building the play button and so forth, until it begins registering the `videojs-flash` hooks, failing to do so (null functions, which bomb when called) and thus ultimately rejecting `rtmp/mp4` as a valid video type.

I also tested older versions of Video.js just to see if there was any difference (it wasn't); even 
### Expected
A live stream from Red5, just as seen on VLC (or other non-browser-based applications).

Note that while searching for an answer I saw lots of old 'live' examples of getting a Red5 stream to be seen by Video.js + videojs-flash, and surprisingly all of them showed the same error — except for one, on a commercial site, which very cleverly hid the configuration details...  
### Actual
On the JS console, patiently going with the debugger through both video.js and videojs-flash.js, I could only understand the following: when it came to register the actual hooks ('middleware') for Flash support via videojs-flash.js, video.js gets null entries for the middleware, and does not check for the validity of the functions it registers; when it comes to launch them to add support for `rtmp/mp4`, it bombs with the error mentioned.

First I tried to change the video type (say, to `video/mp4`) to see what happens. It was clear that what Video.js supports out of the box worked; also, it was clear as well that `rtmp/mp4` support is recognised (= registered!) by Video.js — it knows it's there, it just can't load the proper hooks.

The culprit, as far as I could track it down (my apologies, I'm writing this in the hope that it makes sense to you; I have only been made aware of the mere existence of Video.js a few hours ago, and I'm terrible at debugging my own code, much less the code written by complete strangers; fortunately, Video.js and videojs-flash.js are reasonably well commented, I can follow up the logic behind what is happening, but, not being a professional programmer, I might lack the knowledge to understand why some things are what seems to me unnecessarily convoluted), seems to be `setSourceHelper()`. As far as I can see, the `videojs-flash.js` initialisation seems to be working fine. I can also see that Video.js is correctly parsing all options, passing them along its many objects, making sure that 'Flash' is a valid `techOrder`, redrawing and re-parsing the video object, and so forth. At about the moment it bombs, this is the HTML that the console shows (notice how a lot has been reformatted by Video.js as it should):

https://pastebin.com/gQzhCbPJ

At some point in Video.js, `Player.prototype.src` tries to set the technology that is supported by the middleware, but `setTech(middleware, tech)` returns `undefined` for Flash; this, in turn, means that `setSourceHelper()` will also return `undefined`; and so will `setSource()`; and finally `bound()`('the new function that changes the context') will be set to an undefined function... which, of course, drops the error and stops JS execution.

The Firefox debug console is a bit more verbose, it says:
```
All candidate resources failed to load. Media load paused.
Cannot play media. No decoders for requested formats: rtmp/mp4
```
Also note that the Flash detecting mechanism for Chrome doesn't seem to work.

### Error output
`VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.` — this will actually come from trying to add a middleware that doesn't exist (i.e. undefined), bombing out of Video.js

Firefox additionally says (on the console):
```
All candidate resources failed to load. Media load paused.
Cannot play media. No decoders for requested formats: rtmp/mp4
```
## Additional Information
To deal with the lack of Flash detection under Chrome, I just tweaked the code to answer with a 'fake' version. This will get rid of the 'No compatible source was found for this media.' (which usually appears on top of the poster image with a big X below), and there will be a 'play' button instead, but clicking on it produces absolutely nothing (no handlers are registered for clicking on that button, anyway). The description of my step-by-step run of the debugger still applies, and the console error will be the same. Also note that 'hacking' the version number may have other (unknown) implications and side-effects (i.e. the JS 'believes' that it is able to rely upon a 'found' Flash plugin, but none has really been activated/loaded, or, if it has, it might have a different API, or whatever...)
#### videojs
Mostly tested with 6.2.0 (using the JS debugger), although I've also tested 6.0.0, 5.9, 5.11, and even 4.0.4...
#### browsers
Tested only on Chrome 59.0.3071.115 (64-bit), Firefox (54.0.1 (64-bit)), Safari (10.1.2 (12603.3.6))
Chrome seems not to get detected for Flash like Firefox, so it always fails the detection code (see above comment about 'tweaking' JS to return 'fake' versions...).
All browsers, of course, were set to allow Flash.
#### OSes
macOS Sierra (10.12.6 Beta (16G23a))
### plugins
None

**Comment by GwynethLlewelyn** [comment]
@misteroneill suggested on #25 to include the latest versions of `video.js` and `video-flash.js`, as well as how to properly add `videojs-swf` to the Video.js options, by using the following script inclusions (using the `unpkg.com` CDN):

```html
<script src="https://unpkg.com/video.js@6.2.1/dist/video.min.js"></script>
<script src="https://unpkg.com/videojs-flash@2.0.0/dist/videojs-flash.min.js"></script>
<script>
  videojs.options.flash.swf = 'https://unpkg.com/videojs-swf@5.4.0/dist/video-js.swf';
</script>
```
This unfortunately continues to produce the exact error as before:

```
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. 
itcode: 4
message: "No compatible source was found for this media."
__proto__: Object
MEDIA_ERR_ABORTED: 1
MEDIA_ERR_CUSTOM: 0
MEDIA_ERR_DECODE: 3
MEDIA_ERR_ENCRYPTED: 5
MEDIA_ERR_NETWORK: 2
MEDIA_ERR_SRC_NOT_SUPPORTED: 4
code: 0
message: ""
status: null
constructor: function it(t)__proto__: Object
Ue @ video.min.js:1

  | Ue | @ | video.min.js:formatted:1550
-- | -- | -- | --
  | Ve.error | @ | video.min.js:formatted:1594
  | e.error | @ | video.min.js:formatted:7866
  | (anonymous) | @ | video.min.js:formatted:7753
  | r | @ | video.min.js:formatted:1705
```

**Comment by progredior** [comment]
I have the same issue, rtmp won't play, even with videojs-flash

**Comment by misteroneill** [comment]
It could be that the source is simply not playable by the Flash tech or SWF. I can confirm that [our basic example](https://github.com/videojs/video.js/blob/master/sandbox/flash.html.example) does work, but that's with MP4.

**Comment by progredior** [comment]
I'm happy to report rtmp works fine by simply adding **videojs-flash**, there must've been sth wrong with the way I included files from local npm.

Config that works, for reference:

`<link href="https://unpkg.com/video.js@6.2.5/dist/video-js.min.css" rel="stylesheet">
<script src="https://unpkg.com/video.js@6.2.5/dist/video.min.js"></script>
<script src="https://unpkg.com/videojs-flash@2.0.0/dist/videojs-flash.min.js"></script>

<video class="video-js vjs-default-skin" controls width="640" height="320" data-setup='{"techOrder": ["flash"]}'>
    <source src="rtmp://server.com:1935/live/test" type="rtmp/mp4">
</video>`

**Comment by dasdeck** [comment]
I can not get it to work either. Even the simple example. Always the same error message as the OP.
Seems like the swf file is not even loaded. Shouldn't it show up in the network activities? How would the "flash-tech" even find out that the source is not compatible without even loading flash?
Maybe the stream I'm working with is the problem though, it is some random stream I found on the internet, the thing is it ends with .mov, can this be a problem?
I use this public stream to test:

https://www.hdwplayer.com/rtmp-player/

Cheers!

JM

**Comment by campones** [comment]
I was wondering why some of my users are saying it doesn't works, since I use chrome.. and I have no issue with vod rtmp setup. but indeed it doesn't work at all on firefox..

**Comment by adrhc** [comment]
I have this setup and doesn't work ff or chrome:

<!DOCTYPE html>
<html>
	
<head>
	<link href="/home/adrianpetre/JISR-web/node_modules/video.js/dist/video-js.css" rel="stylesheet">
	<script src="/home/adrianpetre/JISR-web/node_modules/video.js/dist/video.js"></script>
	<script src="/home/adrianpetre/JISR-web/node_modules/videojs-flash/dist/videojs-flash.js"></script>
</head>

<body>
	
  <video id="my-video" class="video-js" data-setup='{"techOrder": ["flash"]}' autoplay controls>
    <source src="rtmp://172.17.20.49:1935/webcam&video1" type="rtmp/flv">
    
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>
</body>
	
</html>

**Comment by gkatsev** [comment]
I just tried making an example in chrome but it wasn't working because Chrome was severely limiting the capabilities of Flash. I think that it hides the fact that flash is available and the tech potentially just doesn't do anything in that case. If I force chrome to load flash it works fine. We might want to remove the check from the tech that checks whether flash is available as a stop-gap so if you use set the player to use the flash tech, it'll just add the object to the page and hope for the best.

**Comment by prasadKodeInCloud** [comment]
Hi Guys,

We were also getting the same error and we were trying to figure out the reason. Then we realized that latest versions of chrome and Firefox automatically block flash by default. We were able to fix the issue by simply allowing flash in website. There was nothing wrong with video.js. Plz refer to the attached screenshot.

![enable-flash](https://user-images.githubusercontent.com/1191679/30470029-b86cb2f2-9a25-11e7-8c47-faac6c208b48.png)

**Comment by vhiltunen** [comment]
@gkatsev that change seems to do the trick making browsers ask for flash and thus, be able to playback rtmp.  Quickly tested on firefox on win7 and edge on win10.

**Comment by CharanRoot** [comment]
@vhiltunen I tried but its not working do you have any public repo or sample code

**Comment by CharanRoot** [comment]
@misteroneill 

i updated your sandbox html file and try to execute in my machine. i was unable to play rtmp mp4 video. 

am i missing something.
`
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Video.js Sandbox</title>

  
  <script src="../node_modules/video.js/dist/ie8/videojs-ie8.js"></script>

  
  <link href="../node_modules/video.js/dist/video-js.css" rel="stylesheet" type="text/css">
  <script src="../node_modules/video.js/dist/video.js"></script>
  <script src="../node_modules/videojs-flash/dist/videojs-flash.js"></script>

  
  <script>
    videojs.options.flash.swf = '../node_modules/videojs-swf/dist/video-js.swf';
  </script>

</head>
<body>


  <video id="vid1" class="video-js vjs-default-skin" controls preload="auto" width="640" height="264" data-setup=''>
       <source src="rtmp://cp67126.edgefcs.net/ondemand/&mp4:mediapm/ovp/content/test/video/spacealonehd_sounas_640_300.mp4" type='rtmp/mp4'>
    <track kind="captions" src="../docs/examples/shared/example-captions.vtt" srclang="en" label="English"></track>
    <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
  </video>

  <script>
    var vid = document.getElementById("vid1");
    var player = videojs(vid, {techOrder: ['flash', 'html5']});
	 player.src([{ 
                type: "rtmp/mp4",
                src: "rtmp://cp67126.edgefcs.net/ondemand/&mp4:mediapm/ovp/content/test/video/spacealonehd_sounas_640_300.mp4"
               }]);
	console.log(player)
  </script>

</body>
</html>`

**Comment by yanxurui** [comment]
I am a newbie to videojs so please forgive my ignorance.

I am using MacOS, with the help of videojs and videojs-flash, it's possible to play  both flv video and rtmp/flv live stream on chrome. But the error `No compatible source was found for this media.` occured on safari and mobile browsers.

I thought the videojs-flash brings flash support to those that don't support it for example safari.
But according to [videojs's doc: How can I play RTMP video in Video.js?](https://github.com/videojs/video.js/blob/master/docs/guides/faq.md#q-how-can-i-play-rtmp-video-in-videojs)
> RTMP requires Flash to play back. You'll need both a browser that supports Flash and the Flash tech.

It means **videojs-flash only works on platforms that already support flash**. It does not work on safari and mobile browsers.
Am I right?
If so, how can I play rtmp/flv on all browsers?
I hope somebody can help me out. Thanks.

**Comment by mister-ben** [comment]
@yanxurui the flash tech enables Video.js to use Flash to play back videos where Flash is installed and available in the browser. It does not emulate Flash itself.

You cannot play rtmp/flv on all browsers. HLS is usually the best replacement for RTMP for live streams, and you can use [videojs-contrib-hls](https://github.com/videojs/videojs-contrib-hls) to play HLS on modern browsers without native support.

**Comment by yanxurui** [comment]
@mister-ben Thank you very much. I see now.

**Comment by NELLIRAJESH** [comment]
Below page may help you to solve the problem.
https://help.ubuntu.com/community/RestrictedFormats
