### ISSUE TITLE
release file doesn't include videojs-flash.js

### ISSUE THREAD

**Issue by bestvow** [videojs/videojs-flash#31]
However npm install version include videojs-flash.js

**Comment by BrandonOCasey** [comment]
Just installed `2.0.1` and it seems that `videojs-flash.js` and `videojs-flash.min.js` are both installed in `node_modules/videojs-flash/dist`

**Comment by gkatsev** [comment]
The npm release is structured such a way that it works with bundlers like browserify and webpack but also has the prebuild files available in the `dist/` folder inside of it. You can also grab these files off of unpkg: `https://unpkg.com/videojs-flash/dist/videojs-flash.js`.

We do have plans to add the dist files to a github release but do not do so currently.
