### ISSUE TITLE
Flash extend Tech issue

### ISSUE THREAD

**Issue by zslucky** [videojs/videojs-flash#32]
## Description
I did follow things in webpack building process, as I think flash now is not default for videojs which version > 6?
```javascript
import videojs from 'video.js';
import Flash from 'videojs-flash';

videojs.registerTech('flash', Flash);
```
But in videojs, it tells me it's not a `Tech`, follow function will return `false` when passing `Flash` in.
```javascript
Tech.isTech = function isTech(component) {
    return component.prototype instanceof Tech || component instanceof Tech || component === Tech;
};
``` 
I think this issue due to different `Tech` class in 2 project, right?

### Expected
Can register `Flash` to videojs

### Actual
As `isTech` return `false`, can't register the flash tech.

#### videojs
6.2.4

#### browsers
Only test on Chrome.

#### OSes
I'm using Mac

### plugins
no other plugins.

**Comment by estevanjantsk** [comment]
Same problem here =(!

**Comment by syagawa** [comment]
I think it is the same as the issue below.
#27

**Comment by zslucky** [comment]
Thanks @syagawa , I think you just solved issue by a workaround. I think it should be a module issue here 😆. 

In my opinion, as `Flash` now is a external tech, it should be register to `videojs` first.

**Comment by syagawa** [comment]
Certainly, registering in the following way is easy to understand.
```js
// in user's js
videojs.registerTech('flash', Flash);
```
However, registration in videojs is being executed in the videojs-flash.js file.
https://github.com/videojs/videojs-flash/blob/0ee005569da4d05ea06814f0f123b149e0e5ebef/src/plugin.js#L1160
Therefore, I think that it is not a problem.

I feel sorry if I misunderstood your intention.
My English ability is not so high.

**Comment by zslucky** [comment]
@syagawa  do you think the `videojs` here we register the tech is the same with the `videojs ` we used in our project?

**Comment by syagawa** [comment]
I also thought it was the same at the first, but it seems to be different.
I tried to use Flash Tech by writing the code below just like you, but it did not work.

```js
//my old js code
import videojs from 'video.js';
import Flash from 'videojs-flash';

var Tech = videojs.getComponent('Tech');
var flash = videojs.extend(Tech, Flash);
videojs.registerTech('Flash', flash);
```

**Comment by zslucky** [comment]
@syagawa , thanks, using `extend` can fix `isTech` issue, but cause another issue...
```javascript
var classCallCheck = function (instance, Constructor) {
  if (!(instance instanceof Constructor)) {
    throw new TypeError("Cannot call a class as a function");
  }
};
```
`instance instanceof Constructor` will return false, then throw error `Cannot call a class as a function`, need a deeper investigation.

**Comment by zslucky** [comment]
![295659fb-be08-42cd-acd4-6a6ce2801cf9](https://user-images.githubusercontent.com/15725589/29487153-67896442-8527-11e7-967d-f6c43fce2dd8.png)
![b9475aff-f02a-4e8b-b58c-82c489c543b1](https://user-images.githubusercontent.com/15725589/29487154-67e36aaa-8527-11e7-8d86-4121ece3000c.png)

**Comment by syagawa** [comment]
Yes, that problem will occur in my previous code.
In webpack it is better to use the script-loader.

```js
// in main.js
import videojs from `video.js`;
import Flash from `videojs-flash`;

var player = videojs('player-id', {techOrder: ['flash']});
```
```js
// in webpack.config.js
module: {
  loaders: [
    {
      test: /videojs-flash\.js$/,
      loader: 'script-loader'
    }
  ]
},
```

**Comment by zslucky** [comment]
@syagawa , you let the script run immediately by `script-loader`, it's OK. But this a workaround without `module`. Maybe a module can make our project more clear. 😄

**Comment by syagawa** [comment]
My method is certainly a "workaround".
I think that it is easier to load in modules, but I could not investigate deeply why the modular way of loading fails.

**Comment by zslucky** [comment]
@syagawa I used `5+` version now... 😢

**Comment by gkatsev** [comment]
You shouldn't need to call `registerTech` yourself. Just importing video.js and then importing videojs-flash should be sufficient.
Also, which webpack and video.js versions are you using? In Video.js <6.2.8, we had a potential ecosystem breakage with our usage of `pkg.module` which was removed in Video.js 6.2.8 where I think webpack ends up loading in video.js twice. Once for video.js using pkg.module and then once for videojs-flash via pkg.main.

**Comment by zslucky** [comment]
@gkatsev thanks, I'm using webpack 3.2.0, and then upgrade video.js to 6.2.8, after just import these 2 modules, I still got `The "flash" tech is undefined` error.

there's a workaround that using `script-loader` to run it first, then it should be correct.

**Comment by gkatsev** [comment]
This the workaround sufficient? Does it work in newer versions of Video.js?
Going to close this since I think it should be ok but we can re-open if there are still issues.
