### ISSUE TITLE
readyState() method not returning value

### ISSUE THREAD

**Issue by Rohitrcp** [videojs/videojs-flash#33]
## Description
Issue for only Flash mode
When I want to get the status of the player by readyState() method it's returning always 0.

Actually, I want to seek last remembered time but in videojs "timeupdate" update event calling before downloaded media content. So I need to get status by readyState() method.

It's working fine if tech order is HTML5 but when I switch in flash mode it's not working.
Please help me

### Expected
I want to status of the player in flash mode so I can seek

### versions
videojs : 6.2.5
videojs-flash: 2.0.0 and swf file used from https://github.com/videojs/video-js-swf
videojs-contrib-hls: 5.8.3

**Comment by nickbreentvnz** [comment]
Possibly related to https://github.com/videojs/video-js-swf/issues/161
