### ISSUE TITLE
Error in IE11, emulation of IE8

### ISSUE THREAD

**Issue by ownmaster** [videojs/videojs-flash#40]
I get an error when I use video.js 6 for IE8 emulation in IE11.

Error:

> SCRIPT5007: Invalid operand to 'in': Object expected
> videojs-flash.js (13,1)
> SCRIPT445: Object doesn't support this action
> video.js (486,3)

Page code:
```
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=8"/>
  <link href="videojs/6/video-js.css" rel="stylesheet">
  <script src="videojs/6/ie8/videojs-ie8.js"></script>
  <script src="videojs/6/videojs-flash.js"></script>
</head>

<body>
  <video id="my-video" class="video-js" controls preload="auto" width="640" height="264" data-setup="{}">
    <source src="video/oceans.mp4" type='video/mp4'>
  </video>

  <script src="videojs/6/video.js"></script>
  <script>
    videojs.options.flash.swf = 'videojs/6/video-js.swf';
  </script>
</body>

```

videojs-plugin: 2.0.1
video.js: 6.2.8
IE11 (in IE8 mode)
Windows 7, 10, 2003

Exactly same page setup (without videojs-flash, of course) works fine with video.js 5. Did I make something wrong? Is it supposed to work at all with video.js 6?

**Comment by gkatsev** [comment]
That's really weird. I don't think we did things that would affect it, but it's possible an innocuous change broke something.
Unfortunately, we don't have the bandwidth to support emulated versions of IE8. However, if you are able to provide a fix, we'd be able to merge it in.

Thanks.
