### ISSUE TITLE
TypeError: 'undefined' is not a function (evaluating 'this.el_.vjs_getProperty(e)')

### ISSUE THREAD

**Issue by Yalhu** [videojs/videojs-flash#43]
## Description
I want to play mp4 on win10 safari, with videojs-flash. There is an error:
`TypeError: 'undefined' is not a function (evaluating 'this.el_.vjs_getProperty(e)')`.
videojs/video.js#2247

## Steps to reproduce
```javascript
var player=videojs('video1',{..});
player.ready(function(){
  setVideoTrack(this);
  ..
});
function setVideoTrack(player){
  player.src([
    //{type:'rtmp/mp4',src:'rtmp://unpkg.com/videojs-swf@5.4.1/dist/video-js.swf/&mp4:path/video.mp4'},
    {type:'video/mp4',src:'video.mp4'}
 ]);
}
```
If I want to enable Streaming Playback ,is the code `{type:'rtmp/mp4',src:'rtmp://unpkg.com/videojs-swf@5.4.1/dist/video-js.swf/&mp4:path/video.mp4'}` right?

## Results
It works well on chrome.But error on win10 safari.
### Expected
mp4 can play on win10 safari.
### Actual
video can't play.
### Error output
TypeError: 'undefined' is not a function (evaluating 'this.el_.vjs_getProperty(e)')

#### videojs 
videojs 6.2,8
#### browsers 
safari 5.1.7
#### OSes 
win10
### plugins
videojs-flash 2.0.1
videojs-contrib-dash 2.9.1

**Comment by mister-ben** [comment]
An RTMP URL should look like `rtmp://example.com/app&mp4:path/to/file.mp4`. It shouldn't not contain the path to the swf, and unpkg.com isn't an RTMP server.

Safari on Windows was discontinued by Apple years ago. I'm not entirely surprised there are issues with a version six major releases behind. Do you have end users who really would use Safari on Windows or are you just testing that in lieu of a current version on Mac OS?

**Comment by Yalhu** [comment]
I just want to know is there any solutions to resolve this problem. All brower work well, except windows safari. I think videojs-flash should work on this, and try testing it. On Mac OS ,I use videojs only ,it works well. I am not afarid there are any users use  Safari on Windows.

**Comment by gkatsev** [comment]
Unfortunately, we cannot support Safari for windows because it's incredibly old and discontinued. I doubt even Adobe supports that browser.
