### ISSUE TITLE
play() does not get queued up when the tech is not ready

### ISSUE THREAD

**Issue by tjaneczko** [videojs/videojs-flash#49]
## Description
From experience, the flash tech does not seem to be fully loaded until the player is visible.  If the player is instantiated while hidden, then made visible and `play()` is called in the same tick, the video does not play.  This is not an issue with the HTML5 tech, not is it an issue with the Flash tech on v5 players.  This seems to only affect v6 players.

## Steps to reproduce

1. Create a video.js player in a hidden div (with `display: none`) using the Flash tech on Windows/IE11
2. Make the div visible and call `play()` on the player in the same tick

### Expected
The `play()` call gets queued up and called again on the tech when the tech is ready.

### Actual
The call to `play()` does not get queued up and the player does not play the video.

### Error output
No errors were observed.

#### videojs
Version 6.3.3 (although it might affect all v6 players)

#### browsers
IE 10, IE 11

#### OSes
Windows

### plugins
No additional plugins are used

## Workaround
It is possible to work around this issue by waiting for the player to be ready before calling play:
```js
const player = videojs('my-player');
player.ready(() => player.play(), true);
```
However from experience with the other techs and with previous versions of the player (along with diving into the source code), it would seem like this should be handled by `play()` anyway.

**Comment by gkatsev** [comment]
We've changed how `play` works in [Video.js 6.5.0](https://github.com/videojs/video.js/blob/master/CHANGELOG.md#650-2017-11-17), would you be able to re-test and see if that fixed it?
Thanks.

**Comment by tjaneczko** [comment]
@gkatsev I'll try to retest and see if that's fixed the issue.  Will let you know!

**Comment by tjaneczko** [comment]
@gkatsev Just tested with Video.js 6.5.1 and it looks like this is fixed!  Thanks for looking into it, I'll go ahead and close this issue.

**Comment by gkatsev** [comment]
Sweet.
