### ISSUE TITLE
videojs-flash  Failed conversion between PP_Var and V8 value

### ISSUE THREAD

**Issue by pinglikethinking** [videojs/videojs-flash#50]
![image](https://user-images.githubusercontent.com/17807157/33258720-7bd308e2-d395-11e7-8f34-0e223d370a70.png)
VM223994:1 Uncaught Error: TypeError: Cannot read property 'open' of undefined
 Uncaught Error: Error: Failed conversion between PP_Var and V8 value

**Comment by pinglikethinking** [comment]
I have solved this.
just delete original [video-js.swf
](https://github.com/mangui/video-js-swf/blob/master/dist/video-js.swf)and
import a new video-js.swf ,put it into static , and use it by `Object.assign({flash: {hls: { withCredentials: false }, swf: '/static/video-js.swf'}}, this.options)`

**Comment by gkatsev** [comment]
That's super weird.
Seems like it's been solved, thanks for posting your fix also.

**Comment by jessefalzone** [comment]
I'm seeing this too, and unfortunately @pinglikethinking's solution didn't solve it.  We only run into the issue when using ES6 imports with Webpack to pull in videojs-flash and videojs-contrib-hls.

We're using the latest versions of everything, I believe:
* video.js@6.6.0
* videojs-flash@2.1.0
* videojs-contrib-hls@5.12.2

FWIW, playback works when we import the packages via <script> tags but this isn't really viable for our project.  We'd like to use them as modules if possible.
