### ISSUE TITLE
Flash wont load as fallback as expect

### ISSUE THREAD

**Issue by wallysson-hotmart** [videojs/videojs-flash#51]
## Description
Should able to render video flash fallback but wont load anything
Test link: https://codepen.io/wallynm/pen/MOxByK

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. Implement actual Flash version into VideoJS
2. Run VideoJS HLS
3. Doesnt load flash falllback

## Results
Doesn't load flash fallback

### Expected
Should render VIdeo with Flash fallback

### Actual
Please describe what actually happened.

### Error output
Doesnt load flash as fallback

## Additional Information
Test link: 
https://codepen.io/wallynm/pen/MOxByK

#### videojs
what version of videojs does this occur with?

#### browsers
what browser are affected?

Chrome Browser wont load flash, even IE wont load it

**Comment by misteroneill** [comment]
I believe this is because videojs-flash cannot play back HLS streams. @forbesjo @gesinger @mjneil can you confirm that's what's happening here?

**Comment by forbesjo** [comment]
I believe this is the same issue as https://github.com/videojs/videojs-flash/issues/26, the flash tech does not have a way to detect that Chrome supports Flash playback so the tech is skipped entirely. We have a PR to fix this #39

**Comment by forbesjo** [comment]
Otherwise the set up looks correct save for the duplicate script tags

**Comment by mister-ben** [comment]
Flash won't work on Codepen as the results are in a sandboxed iframe.
