### ISSUE TITLE
In chrome to play rtmp/flv ??

### ISSUE THREAD

**Issue by ch-zgh-1993** [videojs/videojs-flash#58]
i use the videoJs in chrome 63.0.3239.108. it not work, and it working in the 64.0 beta version.

which i should use ? videoJS or videoJS-flash.js, they would like which the version of chrome? such as the lastest support version.

thank you!

**Comment by gkatsev** [comment]
videojs-flash is a plugin for Video.js that enables playback via Flash. Specifically, it's for version 6 of Video.js, version 5 has it built-in.
What version of video.js and videojs-flash are you using? Can you elaborate on what you mean one version "works" and another "doesn't work"? Are you seeing any errors or just a blank screen? Even better if you can provide a reduced test case.
Thanks.

**Comment by ch-zgh-1993** [comment]
oh, very thanks ,  i understand the banlance.
my problem is when i use videoJs 6.2.8 play rtmp/flv format video, it throw "No compatible source was found for this media" at chrome version 63.0.3239.108 , but it work correct at chorme 64.0 beta version. 
the code is Exactly the same.
thank you very much.

**Comment by gkatsev** [comment]
4.12.5 is a very old version of Video.js that we don't maintain anymore. We just fixed the "no compatible source was found for this media" issue with #39. So, I would recommend updating to latest Video.js and latest videojs-flash.

**Comment by ch-zgh-1993** [comment]
<video id="my-video" class="video-js" controls preload="auto" width="640" height="264"
           poster="poster.png" data-setup="{}">
        <source src="rtmp://10.10.12.187:1935/live/test" type='rtmp/flv'>
        <p class="vjs-no-js">
            To view this video please enable JavaScript, and consider upgrading to a web browser that
            <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
        </p>
    </video>

    
    <script src="http://vjs.zencdn.net/6.4.0/video.js"></script>

i use the lastest version. it not work , and throw the sample error. "No compatible source was found for this media"....
what can i do for this?
very thank you ~!

**Comment by gkatsev** [comment]
You need to include videojs-flash after you've included videojs on the page.

**Comment by ch-zgh-1993** [comment]
i do. but it will need more file to support videojs-flash,  videojs-flash need to config some things , and i will Introduce other files to support videojs-flash.
very thanks!
