### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getComponent' of undefined

### ISSUE THREAD

**Issue by chronokz** [videojs/videojs-flash#63]
On include to a web-page. 
`<script src="https://cdn.jsdelivr.net/npm/videojs-flash@2/dist/videojs-flash.min.js"></script>`
Browser: Chromium, Windows: 10.

**Comment by gkatsev** [comment]
What version of Video.js are you using with this?

**Comment by chronokz** [comment]
The last one from http://videojs.com/getting-started/ 
<link href="http://vjs.zencdn.net/6.6.3/video-js.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/6.6.3/video.js"></script>
