### ISSUE TITLE
Does not work at all?!

### ISSUE THREAD

**Issue by sicLotus** [videojs/videojs-flash#67]
## Description
I want to use Video.js (Version 6.8.0) with flash tech as fallback. In a simple test case the flash player does not work at all. I got no errors nor any information what was wrong. The website loads a flash player but I cant play/start any video.

![image](https://user-images.githubusercontent.com/1172635/37823064-a602eda0-2e88-11e8-9132-14be176b9927.png)

## Steps to reproduce
There are no steps just a simple example. The  video.min.js is the latest version 6.8.0.
```
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="./video-js.css">
		<script type="text/javascript" src="./video.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/videojs-flash@2/dist/videojs-flash.min.js"></script>
	</head>
	<body>
	<video id="my-video" class="video-js" controls preload="none" data-setup="{}">
		<source src="./_mp4test2.mp4">
			<p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
		</video>
		<script type="text/javascript">
			document.addEventListener("DOMContentLoaded", function() {
				var player = videojs('my-video', {techOrder: ['flash', 'html5']});
				player.on('error', function(e) {
					console.log(e);
					e.stopImmediatePropagation();
					var error = this.player().error();
					console.log('error!', error.code, error.type , error.message);
				});         		  
			});
		</script>
	</body>
</html>
```

#### browsers
Chrome and Internet Explorer can't play the video.
Firefox doesn't load a flash player at all.

#### OSes
Windows 10

**Comment by worldking6** [comment]
> ## Description
> I want to use Video.js (Version 6.8.0) with flash tech as fallback. In a simple test case the flash player does not work at all. I got no errors nor any information what was wrong. The website loads a flash player but I cant play/start any video.
> 
> ![image](https://user-images.githubusercontent.com/1172635/37823064-a602eda0-2e88-11e8-9132-14be176b9927.png)
> 
> ## Steps to reproduce
> There are no steps just a simple example. The video.min.js is the latest version 6.8.0.
> 
> ```
> <html>
> 	<head>
> 		<link rel="stylesheet" type="text/css" href="./video-js.css">
> 		<script type="text/javascript" src="./video.min.js"></script>
> 		<script src="https://cdn.jsdelivr.net/npm/videojs-flash@2/dist/videojs-flash.min.js"></script>
> 	</head>
> 	<body>
> 	<video id="my-video" class="video-js" controls preload="none" data-setup="{}">
> 		<source src="./_mp4test2.mp4">
> 			<p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
> 		</video>
> 		<script type="text/javascript">
> 			document.addEventListener("DOMContentLoaded", function() {
> 				var player = videojs('my-video', {techOrder: ['flash', 'html5']});
> 				player.on('error', function(e) {
> 					console.log(e);
> 					e.stopImmediatePropagation();
> 					var error = this.player().error();
> 					console.log('error!', error.code, error.type , error.message);
> 				});         		  
> 			});
> 		</script>
> 	</body>
> </html>
> ```
> #### browsers
> Chrome and Internet Explorer can't play the video.
> Firefox doesn't load a flash player at all.
> 
> #### OSes
> Windows 10

Well,buddy,put you test page into a service environment，then flash will work
