### ISSUE TITLE
How do you test if the fallback really works?

### ISSUE THREAD

**Issue by COLABORATI** [videojs/videojs-flash#73]
I have some strange things going on with this, but first I would like to dig deeper and ask:
how do you test if the flash fallback really works?
In other words: which browser is still not html5 capable and a good target for testing this fallback?

Ye, I know flash is dead, etc. etc. Thanks!

**Comment by gkatsev** [comment]
You can always force it by setting `techOrder: ['flash']` on the player so that only the Flash tech is allowed to run.

**Comment by ldayananda** [comment]
@COLABORATI did that work for your test?

**Comment by worldking6** [comment]
@gkatsev 
hey buudy,I just force it flash on chrome,But as a test,it dose not play any thing...
