### ISSUE TITLE
Chrome auto load flash player when i play hls video

### ISSUE THREAD

**Issue by hackedbyxx** [videojs/videojs-flash#74]
## Description
edge browser is normal,but chrome is different.
```
<video id="my-player" class="video-js" controls preload="auto" poster="6d749fe541988012b9e03cc0d5bc1ec96e51e681b78f17839c6495da47153976.jpg">
        <source src="rtmp://***/live/test" type="rtmp/flv">
        <source src="https://***/hls/test/index.m3u8" type="application/x-mpegURL">
</video>
...
<script type="text/javascript" src="./js/video.min.js"></script>
<script type="text/javascript" src="./js/videojs-contrib-hls.js"></script>
<script type="text/javascript" `src="./js/videojs-flash.min.js"></script>
```

i don't know why,so would you mind help me to resolve it

**Comment by gkatsev** [comment]
chrome basically doesn't let flash to run by default, especially if the size of the swf is too small (I think if it's below 600x400).

**Comment by hackedbyxx** [comment]
@gkatsev yes so i put rtmp before,now the problem is  i push hls,but Chrome use flash player default,edge use h5 player,so edge works normal,chrome use flash player and see nothing
